"""Synthesizer protocol — backing model can swap without touching the pipeline."""
from __future__ import annotations
from typing import Protocol

from kestrel.models import ItemNarrative, RawItem, ScoredItem, Taxonomy, Classification


class Synthesizer(Protocol):
    def classify(self, item: RawItem, taxonomy: Taxonomy) -> Classification: ...
    def top_line(self, items: list[ScoredItem], style: str, max_words: int) -> list[str]: ...
    def enrich_item(self, item: ScoredItem, style: str) -> ItemNarrative: ...
    def watchpoints(self, items: list[ScoredItem], style: str) -> list[str]: ...
